# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6337f788a92d85bd78c84d74bbfc1d87930ddc1a23c3a999885819b5d850eef08b0153e1582e6955f036a5f8daa3769088dc4399f763d8ad2ab1c17db7b74a86

test:
  secret_key_base: df0b0f88a2b3162be1f16b3d1ef863d5197d4e433016c05a24350e25b775cc2e7f87d3c67cc08c27ea34818f0ef56181fbe453ba3ee2c31515ef35f15af284d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
